In [10]:
import pandas as pd
from delai.ml_logic.preprocessing import preprocess_X, preprocess_y
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate

In [11]:
import numpy as np

In [12]:
df = pd.read_csv('../raw_data/train_100k.csv')

In [13]:
df_test = pd.read_csv('../raw_data/initial_X_train.csv')

In [29]:
df_25k = df.head(25000)

In [30]:
X = df_25k.drop(columns = ['Unnamed: 0.1', 'ArrDelayMinutes', 'Cancelled', 'Diverted'])

In [31]:
y = df_25k[['Unnamed: 0','ArrDelayMinutes', 'Cancelled', 'Diverted']]

In [32]:
X_preprocessed = preprocess_X(X)

✅ preprocess_X() done


In [8]:
y_preprocessed = preprocess_y(y)

✅ BINARY preprocess_y() done


/home/mmcgushin/code/sameriliya/delai/delai/ml_logic/preprocessing.py:95: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["DelayGroup"] = None


In [14]:
neigh = KNeighborsClassifier(n_neighbors=22)

In [15]:
scores = cross_validate(neigh, X_preprocessed, y_preprocessed, cv=5, scoring=('accuracy', 'recall_weighted', 'f1_weighted'),
                     return_train_score=True)

In [16]:
scores

{'fit_time': array([0.24984598, 0.07513332, 0.05089164, 0.05053234, 0.09657311]),
 'score_time': array([1.91105771, 1.52175093, 1.4043777 , 1.73473144, 1.94866991]),
 'test_accuracy': array([0.8652, 0.8634, 0.865 , 0.8648, 0.865 ]),
 'train_accuracy': array([0.86535, 0.86625, 0.8659 , 0.86585, 0.86565]),
 'test_recall_weighted': array([0.8652, 0.8634, 0.865 , 0.8648, 0.865 ]),
 'train_recall_weighted': array([0.86535, 0.86625, 0.8659 , 0.86585, 0.86565]),
 'test_f1_weighted': array([0.80362388, 0.80271669, 0.8027571 , 0.80342241, 0.80390268]),
 'train_f1_weighted': array([0.80436388, 0.80595223, 0.80595712, 0.80546547, 0.8048939 ])}

In [17]:
neigh1 = KNeighborsClassifier(n_neighbors=22)

In [18]:
scores = cross_validate(neigh1, X_preprocessed, y_preprocessed, cv=5, scoring=('accuracy', 'recall_weighted', 'f1_weighted', 'precision_weighted'),
                     return_train_score=True)

In [19]:
scores

{'fit_time': array([0.22539735, 0.05540681, 0.0527544 , 0.05203319, 0.05141878]),
 'score_time': array([1.57185268, 1.59137845, 1.52070284, 1.54834032, 1.51535654]),
 'test_accuracy': array([0.8652, 0.8634, 0.865 , 0.8648, 0.865 ]),
 'train_accuracy': array([0.86535, 0.86625, 0.8659 , 0.86585, 0.86565]),
 'test_recall_weighted': array([0.8652, 0.8634, 0.865 , 0.8648, 0.865 ]),
 'train_recall_weighted': array([0.86535, 0.86625, 0.8659 , 0.86585, 0.86565]),
 'test_f1_weighted': array([0.80362388, 0.80271669, 0.8027571 , 0.80342241, 0.80390268]),
 'train_f1_weighted': array([0.80436388, 0.80595223, 0.80595712, 0.80546547, 0.8048939 ]),
 'test_precision_weighted': array([0.80298707, 0.7681658 , 0.74887055, 0.78755764, 0.79972556]),
 'train_precision_weighted': array([0.81451542, 0.84809334, 0.83121561, 0.83256085, 0.8270451 ])}

In [33]:
y_nonbinary = preprocess_y(y, is_binary=False)

✅ STANDARD preprocess_y() done


/home/mmcgushin/code/sameriliya/delai/delai/ml_logic/preprocessing.py:95: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["DelayGroup"] = None


In [60]:
neigh2 = KNeighborsClassifier(n_neighbors=22)

In [61]:
scores = cross_validate(neigh2, X_preprocessed, y_nonbinary, cv=5, scoring=('accuracy', 'recall_weighted', 'f1_weighted', 'precision_weighted'),
                     return_train_score=True)

/home/mmcgushin/.pyenv/versions/3.8.12/envs/delai/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [62]:
scores

{'fit_time': array([0.36060905, 0.04751372, 0.05169606, 0.04987979, 0.04799175]),
 'score_time': array([1.32018423, 1.22875381, 1.26119661, 1.33516788, 1.4232378 ]),
 'test_accuracy': array([0.6492, 0.65  , 0.6442, 0.648 , 0.6472]),
 'train_accuracy': array([0.6567 , 0.65665, 0.6568 , 0.65575, 0.6555 ]),
 'test_recall_weighted': array([0.6492, 0.65  , 0.6442, 0.648 , 0.6472]),
 'train_recall_weighted': array([0.6567 , 0.65665, 0.6568 , 0.65575, 0.6555 ]),
 'test_f1_weighted': array([0.52911014, 0.52916598, 0.52772472, 0.52526379, 0.52828075]),
 'train_f1_weighted': array([0.54031778, 0.54099748, 0.54208199, 0.53872632, 0.5389672 ]),
 'test_precision_weighted': array([0.5584303 , 0.53173274, 0.50933278, 0.54874641, 0.53042763]),
 'train_precision_weighted': array([0.61425413, 0.60867998, 0.61402008, 0.59276653, 0.60375162])}

In [32]:
from tensorflow.keras import *

ModuleNotFoundError: No module named 'tensorflow'

In [25]:
(13339768 + 4336965) / (13339768 + 4336965 + 2166865 + 591652)

0.8650118300485681

In [27]:
y_preprocessed

array([1, 1, 1, ..., 1, 1, 1])

In [28]:
y_nonbinary

array([2, 3, 2, ..., 2, 2, 2])

In [29]:
y_cat = to_categorical(y_nonbinary)

NameError: name 'to_categorical' is not defined

In [34]:
from imblearn.under_sampling import RandomUnderSampler
under_sampler = RandomUnderSampler(random_state=42)

In [35]:
X_res, y_res = under_sampler.fit_resample(X_preprocessed, y_nonbinary)

In [13]:
len(X_res)

26116

In [36]:
len(y_res)

3012

In [37]:
unique, counts = np.unique(y_res, return_counts=True)

In [38]:
unique, counts

(array([0, 1, 2, 3]), array([753, 753, 753, 753]))

In [39]:
neigh3 = KNeighborsClassifier(n_neighbors=22)

In [40]:
scores = cross_validate(neigh3, X_res, y_res, cv=5, scoring=('accuracy', 'recall_weighted', 'f1_weighted', 'precision_weighted'),
                     return_train_score=True, n_jobs=-1)

In [41]:
scores

{'fit_time': array([0.55664754, 0.46056271, 0.46696305, 0.05904675, 0.05322123]),
 'score_time': array([0.19202614, 0.17434883, 0.1296258 , 0.11792445, 0.11355424]),
 'test_accuracy': array([0.36650083, 0.35820896, 0.33887043, 0.34385382, 0.35049834]),
 'train_accuracy': array([0.44209215, 0.43794105, 0.44107884, 0.44273859, 0.4340249 ]),
 'test_recall_weighted': array([0.36650083, 0.35820896, 0.33887043, 0.34385382, 0.35049834]),
 'train_recall_weighted': array([0.44209215, 0.43794105, 0.44107884, 0.44273859, 0.4340249 ]),
 'test_f1_weighted': array([0.35811162, 0.35273768, 0.33679524, 0.3322422 , 0.34046437]),
 'train_f1_weighted': array([0.43803692, 0.43339522, 0.43671847, 0.43781684, 0.42943582]),
 'test_precision_weighted': array([0.36107915, 0.35581867, 0.34134641, 0.3394918 , 0.34374437]),
 'train_precision_weighted': array([0.44418833, 0.44120269, 0.44193741, 0.44595976, 0.43648653])}

In [42]:
neigh4 = KNeighborsClassifier(n_neighbors=22)

In [43]:
scores = cross_validate(neigh3, X_res, y_res, cv=5, scoring=('accuracy', 'recall_weighted', 'f1_weighted', 'precision_weighted'),
                     return_train_score=True, n_jobs=-1)

In [44]:
scores

{'fit_time': array([0.06546593, 0.07304597, 0.56509042, 0.41289234, 0.04316568]),
 'score_time': array([0.10359955, 0.11460996, 0.19915581, 0.12057948, 0.12849021]),
 'test_accuracy': array([0.36650083, 0.35820896, 0.33887043, 0.34385382, 0.35049834]),
 'train_accuracy': array([0.44209215, 0.43794105, 0.44107884, 0.44273859, 0.4340249 ]),
 'test_recall_weighted': array([0.36650083, 0.35820896, 0.33887043, 0.34385382, 0.35049834]),
 'train_recall_weighted': array([0.44209215, 0.43794105, 0.44107884, 0.44273859, 0.4340249 ]),
 'test_f1_weighted': array([0.35811162, 0.35273768, 0.33679524, 0.3322422 , 0.34046437]),
 'train_f1_weighted': array([0.43803692, 0.43339522, 0.43671847, 0.43781684, 0.42943582]),
 'test_precision_weighted': array([0.36107915, 0.35581867, 0.34134641, 0.3394918 , 0.34374437]),
 'train_precision_weighted': array([0.44418833, 0.44120269, 0.44193741, 0.44595976, 0.43648653])}